"""Initial schema

Revision ID: bcb9168d91df
Revises: 
Create Date: 2026-09-15 13:00:01.866926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcb9168d91df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afk_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afk_statuses')),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_afk_guild_user')
    )
    op.create_index(op.f('ix_afk_statuses_guild_id'), 'afk_statuses', ['guild_id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.Column('new_joins', sa.Integer(), nullable=False),
    sa.Column('leaves', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('tickets_opened', sa.Integer(), nullable=False),
    sa.Column('tickets_closed', sa.Integer(), nullable=False),
    sa.Column('mod_actions', sa.Integer(), nullable=False),
    sa.Column('channel_activity', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('role_distribution', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_snapshots')),
    sa.UniqueConstraint('guild_id', 'snapshot_date', name='uq_analytics_snapshots_guild_date')
    )
    op.create_index(op.f('ix_analytics_snapshots_guild_id'), 'analytics_snapshots', ['guild_id'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('appeal_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeals')),
    sa.UniqueConstraint('case_id', name=op.f('uq_appeals_case_id'))
    )
    op.create_table('application_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('app_type', sa.String(length=50), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('review_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('result_role_id', sa.BigInteger(), nullable=True),
    sa.Column('form_fields', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_configs'))
    )
    op.create_index(op.f('ix_application_configs_guild_id'), 'application_configs', ['guild_id'], unique=False)
    op.create_table('application_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_responses'))
    )
    op.create_table('applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applications_guild_id'), 'applications', ['guild_id'], unique=False)
    op.create_table('automations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automations'))
    )
    op.create_index(op.f('ix_automations_guild_id'), 'automations', ['guild_id'], unique=False)
    op.create_table('backup_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('backup_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_snapshots'))
    )
    op.create_table('backups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('backup_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backups'))
    )
    op.create_index(op.f('ix_backups_guild_id'), 'backups', ['guild_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_notes'))
    )
    op.create_table('channel_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('logical_name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('managed_by_bot', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_mappings')),
    sa.UniqueConstraint('guild_id', 'discord_channel_id', name='uq_channel_mappings_guild_discord')
    )
    op.create_index(op.f('ix_channel_mappings_guild_id'), 'channel_mappings', ['guild_id'], unique=False)
    op.create_table('giveaways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('prize', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.BigInteger(), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giveaways'))
    )
    op.create_index(op.f('ix_giveaways_guild_id'), 'giveaways', ['guild_id'], unique=False)
    op.create_table('guild_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('server_type', sa.String(length=20), nullable=True),
    sa.Column('features_enabled', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('mod_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('security_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('rules_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('ticket_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('suggestion_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('report_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_role_ids', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('mod_role_ids', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('admin_role_ids', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('config_locked', sa.Boolean(), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('setup_phase', sa.String(length=20), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_guild_configs'))
    )
    op.create_table('guilds',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_guilds'))
    )
    op.create_table('log_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_events'))
    )
    op.create_index(op.f('ix_log_events_category'), 'log_events', ['category'], unique=False)
    op.create_index(op.f('ix_log_events_created_at'), 'log_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_events_guild_id'), 'log_events', ['guild_id'], unique=False)
    op.create_table('moderation_cases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('case_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_cases'))
    )
    op.create_index('ix_mod_cases_guild_case_num', 'moderation_cases', ['guild_id', 'case_number'], unique=True)
    op.create_index(op.f('ix_moderation_cases_guild_id'), 'moderation_cases', ['guild_id'], unique=False)
    op.create_index(op.f('ix_moderation_cases_user_id'), 'moderation_cases', ['user_id'], unique=False)
    op.create_table('operation_journals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('operation_id', sa.String(length=50), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('step_description', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discord_resource_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_type', sa.String(length=30), nullable=True),
    sa.Column('rollback_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_journals'))
    )
    op.create_index(op.f('ix_operation_journals_guild_id'), 'operation_journals', ['guild_id'], unique=False)
    op.create_index(op.f('ix_operation_journals_operation_id'), 'operation_journals', ['operation_id'], unique=False)
    op.create_table('permission_policies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('allow_bits', sa.BigInteger(), nullable=False),
    sa.Column('deny_bits', sa.BigInteger(), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('managed_by_bot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_policies'))
    )
    op.create_index(op.f('ix_permission_policies_guild_id'), 'permission_policies', ['guild_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_remind_at'), 'reminders', ['remind_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_guild_id'), 'reports', ['guild_id'], unique=False)
    op.create_table('role_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=False),
    sa.Column('logical_name', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('managed_by_bot', sa.Boolean(), nullable=False),
    sa.Column('permissions_preset', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_mappings')),
    sa.UniqueConstraint('guild_id', 'discord_role_id', name='uq_role_mappings_guild_discord')
    )
    op.create_index(op.f('ix_role_mappings_guild_id'), 'role_mappings', ['guild_id'], unique=False)
    op.create_table('role_menus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('max_selections', sa.BigInteger(), nullable=False),
    sa.Column('mutually_exclusive', sa.Boolean(), nullable=False),
    sa.Column('staff_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_menus'))
    )
    op.create_index(op.f('ix_role_menus_guild_id'), 'role_menus', ['guild_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    op.create_index(op.f('ix_scheduled_tasks_guild_id'), 'scheduled_tasks', ['guild_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_run_at'), 'scheduled_tasks', ['run_at'], unique=False)
    op.create_index('ix_scheduled_tasks_run_at_pending', 'scheduled_tasks', ['run_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index(op.f('ix_scheduled_tasks_status'), 'scheduled_tasks', ['status'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index(op.f('ix_security_events_guild_id'), 'security_events', ['guild_id'], unique=False)
    op.create_table('starboard_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('self_star', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_starboard_configs'))
    )
    op.create_table('suggestions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('staff_response', sa.Text(), nullable=True),
    sa.Column('responder_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    op.create_index(op.f('ix_suggestions_guild_id'), 'suggestions', ['guild_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('guild_id', 'name', name='uq_tag_guild_name')
    )
    op.create_index(op.f('ix_tags_guild_id'), 'tags', ['guild_id'], unique=False)
    op.create_table('template_resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_resources'))
    )
    op.create_table('templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_table('ticket_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_type', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_roles', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('max_open_per_user', sa.Integer(), nullable=False),
    sa.Column('inactivity_hours', sa.Integer(), nullable=False),
    sa.Column('auto_close_hours', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('form_fields', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_configs'))
    )
    op.create_index(op.f('ix_ticket_configs_guild_id'), 'ticket_configs', ['guild_id'], unique=False)
    op.create_table('ticket_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_members'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('claimed_by', sa.BigInteger(), nullable=True),
    sa.Column('ticket_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_guild_id'), 'tickets', ['guild_id'], unique=False)
    op.create_table('verification_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('verified_role_id', sa.BigInteger(), nullable=True),
    sa.Column('unverified_role_id', sa.BigInteger(), nullable=True),
    sa.Column('min_account_age_hours', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('rules_text', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_verification_configs_guild_id'))
    )
    op.create_table('warnings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('warning_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warnings'))
    )
    op.create_index(op.f('ix_warnings_guild_id'), 'warnings', ['guild_id'], unique=False)
    op.create_index(op.f('ix_warnings_user_id'), 'warnings', ['user_id'], unique=False)
    op.create_table('webhook_trackings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('webhook_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_bot_managed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_trackings'))
    )
    op.create_index(op.f('ix_webhook_trackings_guild_id'), 'webhook_trackings', ['guild_id'], unique=False)
    op.create_table('giveaway_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('giveaway_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('fk_giveaway_entries_giveaway_id_giveaways'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giveaway_entries')),
    sa.UniqueConstraint('giveaway_id', 'user_id', name='uq_giveaway_user')
    )
    op.create_index(op.f('ix_giveaway_entries_giveaway_id'), 'giveaway_entries', ['giveaway_id'], unique=False)
    op.create_table('starboard_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('original_message_id', sa.BigInteger(), nullable=False),
    sa.Column('starboard_message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['starboard_configs.guild_id'], name=op.f('fk_starboard_entries_guild_id_starboard_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_starboard_entries')),
    sa.UniqueConstraint('original_message_id', name=op.f('uq_starboard_entries_original_message_id'))
    )
    op.create_index(op.f('ix_starboard_entries_guild_id'), 'starboard_entries', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_starboard_entries_guild_id'), table_name='starboard_entries')
    op.drop_table('starboard_entries')
    op.drop_index(op.f('ix_giveaway_entries_giveaway_id'), table_name='giveaway_entries')
    op.drop_table('giveaway_entries')
    op.drop_index(op.f('ix_webhook_trackings_guild_id'), table_name='webhook_trackings')
    op.drop_table('webhook_trackings')
    op.drop_index(op.f('ix_warnings_user_id'), table_name='warnings')
    op.drop_index(op.f('ix_warnings_guild_id'), table_name='warnings')
    op.drop_table('warnings')
    op.drop_table('verification_configs')
    op.drop_index(op.f('ix_tickets_guild_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('ticket_members')
    op.drop_index(op.f('ix_ticket_configs_guild_id'), table_name='ticket_configs')
    op.drop_table('ticket_configs')
    op.drop_table('templates')
    op.drop_table('template_resources')
    op.drop_index(op.f('ix_tags_guild_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_suggestions_guild_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_table('starboard_configs')
    op.drop_index(op.f('ix_security_events_guild_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_scheduled_tasks_status'), table_name='scheduled_tasks')
    op.drop_index('ix_scheduled_tasks_run_at_pending', table_name='scheduled_tasks', postgresql_where="status = 'pending'")
    op.drop_index(op.f('ix_scheduled_tasks_run_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_guild_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_role_menus_guild_id'), table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_index(op.f('ix_role_mappings_guild_id'), table_name='role_mappings')
    op.drop_table('role_mappings')
    op.drop_index(op.f('ix_reports_guild_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_remind_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_permission_policies_guild_id'), table_name='permission_policies')
    op.drop_table('permission_policies')
    op.drop_index(op.f('ix_operation_journals_operation_id'), table_name='operation_journals')
    op.drop_index(op.f('ix_operation_journals_guild_id'), table_name='operation_journals')
    op.drop_table('operation_journals')
    op.drop_index(op.f('ix_moderation_cases_user_id'), table_name='moderation_cases')
    op.drop_index(op.f('ix_moderation_cases_guild_id'), table_name='moderation_cases')
    op.drop_index('ix_mod_cases_guild_case_num', table_name='moderation_cases')
    op.drop_table('moderation_cases')
    op.drop_index(op.f('ix_log_events_guild_id'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_created_at'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_category'), table_name='log_events')
    op.drop_table('log_events')
    op.drop_table('guilds')
    op.drop_table('guild_configs')
    op.drop_index(op.f('ix_giveaways_guild_id'), table_name='giveaways')
    op.drop_table('giveaways')
    op.drop_index(op.f('ix_channel_mappings_guild_id'), table_name='channel_mappings')
    op.drop_table('channel_mappings')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_backups_guild_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_table('backup_snapshots')
    op.drop_index(op.f('ix_automations_guild_id'), table_name='automations')
    op.drop_table('automations')
    op.drop_index(op.f('ix_applications_guild_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('application_responses')
    op.drop_index(op.f('ix_application_configs_guild_id'), table_name='application_configs')
    op.drop_table('application_configs')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_analytics_snapshots_guild_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_afk_statuses_guild_id'), table_name='afk_statuses')
    op.drop_table('afk_statuses')
    # ### end Alembic commands ###
